apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tpt-gov-uploads-pvc
  namespace: tpt-gov
  labels:
    app: tpt-government-platform
    component: storage
    type: uploads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tpt-gov-logs-pvc
  namespace: tpt-gov
  labels:
    app: tpt-government-platform
    component: storage
    type: logs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tpt-gov-cache-pvc
  namespace: tpt-gov
  labels:
    app: tpt-government-platform
    component: storage
    type: cache
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tpt-gov-backup-pvc
  namespace: tpt-gov
  labels:
    app: tpt-government-platform
    component: storage
    type: backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: backup-storage
---
# StorageClass definitions (if not pre-defined in cluster)
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-ssd
  labels:
    app: tpt-government-platform
    component: storage-class
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"
  kmsKeyId: alias/aws/ebs
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  labels:
    app: tpt-government-platform
    component: storage-class
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
  encrypted: "true"
  kmsKeyId: alias/aws/ebs
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: backup-storage
  labels:
    app: tpt-government-platform
    component: storage-class
provisioner: kubernetes.io/aws-ebs
parameters:
  type: st1
  fsType: ext4
  encrypted: "true"
  kmsKeyId: alias/aws/ebs
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
